# fly.toml app configuration file generated for noteplanning-backend

app = "noteplanning-backend"
primary_region = "gru"  # São Paulo region (updated from deprecated gig)

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  HOST = "0.0.0.0"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[[vm.regions]]
  region = "gru"

[deploy]
  release_command = "npx prisma migrate deploy"
